sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 5967877658d900fa446c68e5f7f2c9027a24bda5
  keep-history: true
  on:
    branch: master
